// Objective-C API for talking to rn-outline/modules/outline-api/go Go package.
//   gobind -lang=objc rn-outline/modules/outline-api/go
//
// File is generated by gobind. Do not edit.

#ifndef __OutlineApiGo_H__
#define __OutlineApiGo_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull OutlineApiGoHello(void);

#endif
