
// Objective-C API for talking to the following Go packages
//
//	outline-api-go
//
// File is generated by gomobile bind. Do not edit.
#ifndef __OutlineApiGo_FRAMEWORK_H__
#define __OutlineApiGo_FRAMEWORK_H__

#include "OutlineApiGo.objc.h"
#include "Universe.objc.h"

#endif
